// Code generated by MockGen. DO NOT EDIT.
// Source: entry_service.go
//
// Generated by this command:
//
//	mockgen -source=entry_service.go -destination=mock/entry_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	service "gist/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEntryService is a mock of EntryService interface.
type MockEntryService struct {
	ctrl     *gomock.Controller
	recorder *MockEntryServiceMockRecorder
	isgomock struct{}
}

// MockEntryServiceMockRecorder is the mock recorder for MockEntryService.
type MockEntryServiceMockRecorder struct {
	mock *MockEntryService
}

// NewMockEntryService creates a new mock instance.
func NewMockEntryService(ctrl *gomock.Controller) *MockEntryService {
	mock := &MockEntryService{ctrl: ctrl}
	mock.recorder = &MockEntryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryService) EXPECT() *MockEntryServiceMockRecorder {
	return m.recorder
}

// ClearEntryCache mocks base method.
func (m *MockEntryService) ClearEntryCache(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearEntryCache", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearEntryCache indicates an expected call of ClearEntryCache.
func (mr *MockEntryServiceMockRecorder) ClearEntryCache(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearEntryCache", reflect.TypeOf((*MockEntryService)(nil).ClearEntryCache), ctx)
}

// ClearReadabilityCache mocks base method.
func (m *MockEntryService) ClearReadabilityCache(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearReadabilityCache", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearReadabilityCache indicates an expected call of ClearReadabilityCache.
func (mr *MockEntryServiceMockRecorder) ClearReadabilityCache(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearReadabilityCache", reflect.TypeOf((*MockEntryService)(nil).ClearReadabilityCache), ctx)
}

// GetByID mocks base method.
func (m *MockEntryService) GetByID(ctx context.Context, id int64) (model.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEntryServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEntryService)(nil).GetByID), ctx, id)
}

// GetStarredCount mocks base method.
func (m *MockEntryService) GetStarredCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStarredCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStarredCount indicates an expected call of GetStarredCount.
func (mr *MockEntryServiceMockRecorder) GetStarredCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStarredCount", reflect.TypeOf((*MockEntryService)(nil).GetStarredCount), ctx)
}

// GetUnreadCounts mocks base method.
func (m *MockEntryService) GetUnreadCounts(ctx context.Context) (map[int64]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadCounts", ctx)
	ret0, _ := ret[0].(map[int64]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadCounts indicates an expected call of GetUnreadCounts.
func (mr *MockEntryServiceMockRecorder) GetUnreadCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadCounts", reflect.TypeOf((*MockEntryService)(nil).GetUnreadCounts), ctx)
}

// List mocks base method.
func (m *MockEntryService) List(ctx context.Context, params service.EntryListParams) ([]model.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]model.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEntryServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEntryService)(nil).List), ctx, params)
}

// MarkAllAsRead mocks base method.
func (m *MockEntryService) MarkAllAsRead(ctx context.Context, feedID, folderID *int64, contentType *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsRead", ctx, feedID, folderID, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllAsRead indicates an expected call of MarkAllAsRead.
func (mr *MockEntryServiceMockRecorder) MarkAllAsRead(ctx, feedID, folderID, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsRead", reflect.TypeOf((*MockEntryService)(nil).MarkAllAsRead), ctx, feedID, folderID, contentType)
}

// MarkAsRead mocks base method.
func (m *MockEntryService) MarkAsRead(ctx context.Context, id int64, read bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, id, read)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockEntryServiceMockRecorder) MarkAsRead(ctx, id, read any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockEntryService)(nil).MarkAsRead), ctx, id, read)
}

// MarkAsStarred mocks base method.
func (m *MockEntryService) MarkAsStarred(ctx context.Context, id int64, starred bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsStarred", ctx, id, starred)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsStarred indicates an expected call of MarkAsStarred.
func (mr *MockEntryServiceMockRecorder) MarkAsStarred(ctx, id, starred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsStarred", reflect.TypeOf((*MockEntryService)(nil).MarkAsStarred), ctx, id, starred)
}

// MarkManyAsRead mocks base method.
func (m *MockEntryService) MarkManyAsRead(ctx context.Context, ids []int64, read bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkManyAsRead", ctx, ids, read)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkManyAsRead indicates an expected call of MarkManyAsRead.
func (mr *MockEntryServiceMockRecorder) MarkManyAsRead(ctx, ids, read any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkManyAsRead", reflect.TypeOf((*MockEntryService)(nil).MarkManyAsRead), ctx, ids, read)
}
