// Code generated by MockGen. DO NOT EDIT.
// Source: feed_service.go
//
// Generated by this command:
//
//	mockgen -source=feed_service.go -destination=mock/feed_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	service "gist/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFeedService is a mock of FeedService interface.
type MockFeedService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServiceMockRecorder
	isgomock struct{}
}

// MockFeedServiceMockRecorder is the mock recorder for MockFeedService.
type MockFeedServiceMockRecorder struct {
	mock *MockFeedService
}

// NewMockFeedService creates a new mock instance.
func NewMockFeedService(ctrl *gomock.Controller) *MockFeedService {
	mock := &MockFeedService{ctrl: ctrl}
	mock.recorder = &MockFeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedService) EXPECT() *MockFeedServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockFeedService) Add(ctx context.Context, feedURL string, folderID *int64, titleOverride, feedType string) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, feedURL, folderID, titleOverride, feedType)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockFeedServiceMockRecorder) Add(ctx, feedURL, folderID, titleOverride, feedType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockFeedService)(nil).Add), ctx, feedURL, folderID, titleOverride, feedType)
}

// AddWithoutFetch mocks base method.
func (m *MockFeedService) AddWithoutFetch(ctx context.Context, feedURL string, folderID *int64, titleOverride, feedType string) (model.Feed, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWithoutFetch", ctx, feedURL, folderID, titleOverride, feedType)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddWithoutFetch indicates an expected call of AddWithoutFetch.
func (mr *MockFeedServiceMockRecorder) AddWithoutFetch(ctx, feedURL, folderID, titleOverride, feedType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWithoutFetch", reflect.TypeOf((*MockFeedService)(nil).AddWithoutFetch), ctx, feedURL, folderID, titleOverride, feedType)
}

// Delete mocks base method.
func (m *MockFeedService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeedServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeedService)(nil).Delete), ctx, id)
}

// DeleteBatch mocks base method.
func (m *MockFeedService) DeleteBatch(ctx context.Context, ids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockFeedServiceMockRecorder) DeleteBatch(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockFeedService)(nil).DeleteBatch), ctx, ids)
}

// List mocks base method.
func (m *MockFeedService) List(ctx context.Context, folderID *int64) ([]model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, folderID)
	ret0, _ := ret[0].([]model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFeedServiceMockRecorder) List(ctx, folderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFeedService)(nil).List), ctx, folderID)
}

// Preview mocks base method.
func (m *MockFeedService) Preview(ctx context.Context, feedURL string) (service.FeedPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", ctx, feedURL)
	ret0, _ := ret[0].(service.FeedPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preview indicates an expected call of Preview.
func (mr *MockFeedServiceMockRecorder) Preview(ctx, feedURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockFeedService)(nil).Preview), ctx, feedURL)
}

// Update mocks base method.
func (m *MockFeedService) Update(ctx context.Context, id int64, title string, folderID *int64, summaryPromptReminder *string) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, title, folderID, summaryPromptReminder)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFeedServiceMockRecorder) Update(ctx, id, title, folderID, summaryPromptReminder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeedService)(nil).Update), ctx, id, title, folderID, summaryPromptReminder)
}

// UpdateType mocks base method.
func (m *MockFeedService) UpdateType(ctx context.Context, id int64, feedType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateType", ctx, id, feedType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateType indicates an expected call of UpdateType.
func (mr *MockFeedServiceMockRecorder) UpdateType(ctx, id, feedType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateType", reflect.TypeOf((*MockFeedService)(nil).UpdateType), ctx, id, feedType)
}

// UpdateViewMode mocks base method.
func (m *MockFeedService) UpdateViewMode(ctx context.Context, id int64, viewMode *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateViewMode", ctx, id, viewMode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateViewMode indicates an expected call of UpdateViewMode.
func (mr *MockFeedServiceMockRecorder) UpdateViewMode(ctx, id, viewMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateViewMode", reflect.TypeOf((*MockFeedService)(nil).UpdateViewMode), ctx, id, viewMode)
}
