// Code generated by MockGen. DO NOT EDIT.
// Source: settings_service.go
//
// Generated by this command:
//
//	mockgen -source=settings_service.go -destination=mock/settings_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	service "gist/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingsService is a mock of SettingsService interface.
type MockSettingsService struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsServiceMockRecorder
	isgomock struct{}
}

// MockSettingsServiceMockRecorder is the mock recorder for MockSettingsService.
type MockSettingsServiceMockRecorder struct {
	mock *MockSettingsService
}

// NewMockSettingsService creates a new mock instance.
func NewMockSettingsService(ctrl *gomock.Controller) *MockSettingsService {
	mock := &MockSettingsService{ctrl: ctrl}
	mock.recorder = &MockSettingsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsService) EXPECT() *MockSettingsServiceMockRecorder {
	return m.recorder
}

// ClearAnubisCookies mocks base method.
func (m *MockSettingsService) ClearAnubisCookies(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAnubisCookies", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearAnubisCookies indicates an expected call of ClearAnubisCookies.
func (mr *MockSettingsServiceMockRecorder) ClearAnubisCookies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAnubisCookies", reflect.TypeOf((*MockSettingsService)(nil).ClearAnubisCookies), ctx)
}

// GetAISettings mocks base method.
func (m *MockSettingsService) GetAISettings(ctx context.Context) (*service.AISettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAISettings", ctx)
	ret0, _ := ret[0].(*service.AISettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAISettings indicates an expected call of GetAISettings.
func (mr *MockSettingsServiceMockRecorder) GetAISettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAISettings", reflect.TypeOf((*MockSettingsService)(nil).GetAISettings), ctx)
}

// GetAppearanceSettings mocks base method.
func (m *MockSettingsService) GetAppearanceSettings(ctx context.Context) (*service.AppearanceSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppearanceSettings", ctx)
	ret0, _ := ret[0].(*service.AppearanceSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppearanceSettings indicates an expected call of GetAppearanceSettings.
func (mr *MockSettingsServiceMockRecorder) GetAppearanceSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppearanceSettings", reflect.TypeOf((*MockSettingsService)(nil).GetAppearanceSettings), ctx)
}

// GetFallbackUserAgent mocks base method.
func (m *MockSettingsService) GetFallbackUserAgent(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFallbackUserAgent", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFallbackUserAgent indicates an expected call of GetFallbackUserAgent.
func (mr *MockSettingsServiceMockRecorder) GetFallbackUserAgent(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFallbackUserAgent", reflect.TypeOf((*MockSettingsService)(nil).GetFallbackUserAgent), ctx)
}

// GetGeneralSettings mocks base method.
func (m *MockSettingsService) GetGeneralSettings(ctx context.Context) (*service.GeneralSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralSettings", ctx)
	ret0, _ := ret[0].(*service.GeneralSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralSettings indicates an expected call of GetGeneralSettings.
func (mr *MockSettingsServiceMockRecorder) GetGeneralSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralSettings", reflect.TypeOf((*MockSettingsService)(nil).GetGeneralSettings), ctx)
}

// GetIPStack mocks base method.
func (m *MockSettingsService) GetIPStack(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPStack", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIPStack indicates an expected call of GetIPStack.
func (mr *MockSettingsServiceMockRecorder) GetIPStack(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPStack", reflect.TypeOf((*MockSettingsService)(nil).GetIPStack), ctx)
}

// GetNetworkSettings mocks base method.
func (m *MockSettingsService) GetNetworkSettings(ctx context.Context) (*service.NetworkSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkSettings", ctx)
	ret0, _ := ret[0].(*service.NetworkSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkSettings indicates an expected call of GetNetworkSettings.
func (mr *MockSettingsServiceMockRecorder) GetNetworkSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkSettings", reflect.TypeOf((*MockSettingsService)(nil).GetNetworkSettings), ctx)
}

// GetProxyURL mocks base method.
func (m *MockSettingsService) GetProxyURL(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyURL", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetProxyURL indicates an expected call of GetProxyURL.
func (mr *MockSettingsServiceMockRecorder) GetProxyURL(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyURL", reflect.TypeOf((*MockSettingsService)(nil).GetProxyURL), ctx)
}

// SetAISettings mocks base method.
func (m *MockSettingsService) SetAISettings(ctx context.Context, settings *service.AISettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAISettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAISettings indicates an expected call of SetAISettings.
func (mr *MockSettingsServiceMockRecorder) SetAISettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAISettings", reflect.TypeOf((*MockSettingsService)(nil).SetAISettings), ctx, settings)
}

// SetAppearanceSettings mocks base method.
func (m *MockSettingsService) SetAppearanceSettings(ctx context.Context, settings *service.AppearanceSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAppearanceSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAppearanceSettings indicates an expected call of SetAppearanceSettings.
func (mr *MockSettingsServiceMockRecorder) SetAppearanceSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppearanceSettings", reflect.TypeOf((*MockSettingsService)(nil).SetAppearanceSettings), ctx, settings)
}

// SetGeneralSettings mocks base method.
func (m *MockSettingsService) SetGeneralSettings(ctx context.Context, settings *service.GeneralSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGeneralSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGeneralSettings indicates an expected call of SetGeneralSettings.
func (mr *MockSettingsServiceMockRecorder) SetGeneralSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGeneralSettings", reflect.TypeOf((*MockSettingsService)(nil).SetGeneralSettings), ctx, settings)
}

// SetNetworkSettings mocks base method.
func (m *MockSettingsService) SetNetworkSettings(ctx context.Context, settings *service.NetworkSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNetworkSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNetworkSettings indicates an expected call of SetNetworkSettings.
func (mr *MockSettingsServiceMockRecorder) SetNetworkSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNetworkSettings", reflect.TypeOf((*MockSettingsService)(nil).SetNetworkSettings), ctx, settings)
}

// TestAI mocks base method.
func (m *MockSettingsService) TestAI(ctx context.Context, provider, apiKey, baseURL, model string, requestOptions map[string]any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestAI", ctx, provider, apiKey, baseURL, model, requestOptions)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestAI indicates an expected call of TestAI.
func (mr *MockSettingsServiceMockRecorder) TestAI(ctx, provider, apiKey, baseURL, model, requestOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestAI", reflect.TypeOf((*MockSettingsService)(nil).TestAI), ctx, provider, apiKey, baseURL, model, requestOptions)
}
