// Code generated by MockGen. DO NOT EDIT.
// Source: entry_repository.go
//
// Generated by this command:
//
//	mockgen -source=entry_repository.go -destination=mock/entry_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	repository "gist/backend/internal/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEntryRepository is a mock of EntryRepository interface.
type MockEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntryRepositoryMockRecorder
	isgomock struct{}
}

// MockEntryRepositoryMockRecorder is the mock recorder for MockEntryRepository.
type MockEntryRepositoryMockRecorder struct {
	mock *MockEntryRepository
}

// NewMockEntryRepository creates a new mock instance.
func NewMockEntryRepository(ctrl *gomock.Controller) *MockEntryRepository {
	mock := &MockEntryRepository{ctrl: ctrl}
	mock.recorder = &MockEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryRepository) EXPECT() *MockEntryRepositoryMockRecorder {
	return m.recorder
}

// ClearAllReadableContent mocks base method.
func (m *MockEntryRepository) ClearAllReadableContent(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAllReadableContent", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearAllReadableContent indicates an expected call of ClearAllReadableContent.
func (mr *MockEntryRepositoryMockRecorder) ClearAllReadableContent(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAllReadableContent", reflect.TypeOf((*MockEntryRepository)(nil).ClearAllReadableContent), ctx)
}

// CreateOrUpdate mocks base method.
func (m *MockEntryRepository) CreateOrUpdate(ctx context.Context, entry model.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate.
func (mr *MockEntryRepositoryMockRecorder) CreateOrUpdate(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockEntryRepository)(nil).CreateOrUpdate), ctx, entry)
}

// DeleteUnstarred mocks base method.
func (m *MockEntryRepository) DeleteUnstarred(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUnstarred", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUnstarred indicates an expected call of DeleteUnstarred.
func (mr *MockEntryRepositoryMockRecorder) DeleteUnstarred(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUnstarred", reflect.TypeOf((*MockEntryRepository)(nil).DeleteUnstarred), ctx)
}

// ExistsByHash mocks base method.
func (m *MockEntryRepository) ExistsByHash(ctx context.Context, feedID int64, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByHash", ctx, feedID, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByHash indicates an expected call of ExistsByHash.
func (mr *MockEntryRepositoryMockRecorder) ExistsByHash(ctx, feedID, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByHash", reflect.TypeOf((*MockEntryRepository)(nil).ExistsByHash), ctx, feedID, hash)
}

// ExistsByLegacyURL mocks base method.
func (m *MockEntryRepository) ExistsByLegacyURL(ctx context.Context, feedID int64, rawURL, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByLegacyURL", ctx, feedID, rawURL, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByLegacyURL indicates an expected call of ExistsByLegacyURL.
func (mr *MockEntryRepositoryMockRecorder) ExistsByLegacyURL(ctx, feedID, rawURL, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByLegacyURL", reflect.TypeOf((*MockEntryRepository)(nil).ExistsByLegacyURL), ctx, feedID, rawURL, hash)
}

// GetAllUnreadCounts mocks base method.
func (m *MockEntryRepository) GetAllUnreadCounts(ctx context.Context) ([]repository.UnreadCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUnreadCounts", ctx)
	ret0, _ := ret[0].([]repository.UnreadCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUnreadCounts indicates an expected call of GetAllUnreadCounts.
func (mr *MockEntryRepositoryMockRecorder) GetAllUnreadCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUnreadCounts", reflect.TypeOf((*MockEntryRepository)(nil).GetAllUnreadCounts), ctx)
}

// GetByID mocks base method.
func (m *MockEntryRepository) GetByID(ctx context.Context, id int64) (model.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEntryRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEntryRepository)(nil).GetByID), ctx, id)
}

// GetStarredCount mocks base method.
func (m *MockEntryRepository) GetStarredCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStarredCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStarredCount indicates an expected call of GetStarredCount.
func (mr *MockEntryRepositoryMockRecorder) GetStarredCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStarredCount", reflect.TypeOf((*MockEntryRepository)(nil).GetStarredCount), ctx)
}

// List mocks base method.
func (m *MockEntryRepository) List(ctx context.Context, filter repository.EntryListFilter) ([]model.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]model.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEntryRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEntryRepository)(nil).List), ctx, filter)
}

// MarkAllAsRead mocks base method.
func (m *MockEntryRepository) MarkAllAsRead(ctx context.Context, feedID, folderID *int64, contentType *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsRead", ctx, feedID, folderID, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllAsRead indicates an expected call of MarkAllAsRead.
func (mr *MockEntryRepositoryMockRecorder) MarkAllAsRead(ctx, feedID, folderID, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsRead", reflect.TypeOf((*MockEntryRepository)(nil).MarkAllAsRead), ctx, feedID, folderID, contentType)
}

// UpdateManyReadStatus mocks base method.
func (m *MockEntryRepository) UpdateManyReadStatus(ctx context.Context, ids []int64, read bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateManyReadStatus", ctx, ids, read)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateManyReadStatus indicates an expected call of UpdateManyReadStatus.
func (mr *MockEntryRepositoryMockRecorder) UpdateManyReadStatus(ctx, ids, read any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateManyReadStatus", reflect.TypeOf((*MockEntryRepository)(nil).UpdateManyReadStatus), ctx, ids, read)
}

// UpdateReadStatus mocks base method.
func (m *MockEntryRepository) UpdateReadStatus(ctx context.Context, id int64, read bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReadStatus", ctx, id, read)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReadStatus indicates an expected call of UpdateReadStatus.
func (mr *MockEntryRepositoryMockRecorder) UpdateReadStatus(ctx, id, read any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReadStatus", reflect.TypeOf((*MockEntryRepository)(nil).UpdateReadStatus), ctx, id, read)
}

// UpdateReadableContent mocks base method.
func (m *MockEntryRepository) UpdateReadableContent(ctx context.Context, id int64, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReadableContent", ctx, id, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReadableContent indicates an expected call of UpdateReadableContent.
func (mr *MockEntryRepositoryMockRecorder) UpdateReadableContent(ctx, id, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReadableContent", reflect.TypeOf((*MockEntryRepository)(nil).UpdateReadableContent), ctx, id, content)
}

// UpdateStarredStatus mocks base method.
func (m *MockEntryRepository) UpdateStarredStatus(ctx context.Context, id int64, starred bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStarredStatus", ctx, id, starred)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStarredStatus indicates an expected call of UpdateStarredStatus.
func (mr *MockEntryRepositoryMockRecorder) UpdateStarredStatus(ctx, id, starred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStarredStatus", reflect.TypeOf((*MockEntryRepository)(nil).UpdateStarredStatus), ctx, id, starred)
}

// MockentryScanner is a mock of entryScanner interface.
type MockentryScanner struct {
	ctrl     *gomock.Controller
	recorder *MockentryScannerMockRecorder
	isgomock struct{}
}

// MockentryScannerMockRecorder is the mock recorder for MockentryScanner.
type MockentryScannerMockRecorder struct {
	mock *MockentryScanner
}

// NewMockentryScanner creates a new mock instance.
func NewMockentryScanner(ctrl *gomock.Controller) *MockentryScanner {
	mock := &MockentryScanner{ctrl: ctrl}
	mock.recorder = &MockentryScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockentryScanner) EXPECT() *MockentryScannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockentryScanner) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockentryScannerMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockentryScanner)(nil).Scan), dest...)
}
