// Code generated by MockGen. DO NOT EDIT.
// Source: feed_repository.go
//
// Generated by this command:
//
//	mockgen -source=feed_repository.go -destination=mock/feed_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFeedRepository is a mock of FeedRepository interface.
type MockFeedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedRepositoryMockRecorder
	isgomock struct{}
}

// MockFeedRepositoryMockRecorder is the mock recorder for MockFeedRepository.
type MockFeedRepositoryMockRecorder struct {
	mock *MockFeedRepository
}

// NewMockFeedRepository creates a new mock instance.
func NewMockFeedRepository(ctrl *gomock.Controller) *MockFeedRepository {
	mock := &MockFeedRepository{ctrl: ctrl}
	mock.recorder = &MockFeedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedRepository) EXPECT() *MockFeedRepositoryMockRecorder {
	return m.recorder
}

// ClearAllConditionalGet mocks base method.
func (m *MockFeedRepository) ClearAllConditionalGet(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAllConditionalGet", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearAllConditionalGet indicates an expected call of ClearAllConditionalGet.
func (mr *MockFeedRepositoryMockRecorder) ClearAllConditionalGet(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAllConditionalGet", reflect.TypeOf((*MockFeedRepository)(nil).ClearAllConditionalGet), ctx)
}

// ClearAllIconPaths mocks base method.
func (m *MockFeedRepository) ClearAllIconPaths(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAllIconPaths", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearAllIconPaths indicates an expected call of ClearAllIconPaths.
func (mr *MockFeedRepositoryMockRecorder) ClearAllIconPaths(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAllIconPaths", reflect.TypeOf((*MockFeedRepository)(nil).ClearAllIconPaths), ctx)
}

// Create mocks base method.
func (m *MockFeedRepository) Create(ctx context.Context, feed model.Feed) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, feed)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFeedRepositoryMockRecorder) Create(ctx, feed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeedRepository)(nil).Create), ctx, feed)
}

// Delete mocks base method.
func (m *MockFeedRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeedRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeedRepository)(nil).Delete), ctx, id)
}

// DeleteBatch mocks base method.
func (m *MockFeedRepository) DeleteBatch(ctx context.Context, ids []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockFeedRepositoryMockRecorder) DeleteBatch(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockFeedRepository)(nil).DeleteBatch), ctx, ids)
}

// FindByURL mocks base method.
func (m *MockFeedRepository) FindByURL(ctx context.Context, url string) (*model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByURL", ctx, url)
	ret0, _ := ret[0].(*model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByURL indicates an expected call of FindByURL.
func (mr *MockFeedRepositoryMockRecorder) FindByURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByURL", reflect.TypeOf((*MockFeedRepository)(nil).FindByURL), ctx, url)
}

// GetByID mocks base method.
func (m *MockFeedRepository) GetByID(ctx context.Context, id int64) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFeedRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFeedRepository)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockFeedRepository) GetByIDs(ctx context.Context, ids []int64) ([]model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockFeedRepositoryMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockFeedRepository)(nil).GetByIDs), ctx, ids)
}

// List mocks base method.
func (m *MockFeedRepository) List(ctx context.Context, folderID *int64) ([]model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, folderID)
	ret0, _ := ret[0].([]model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFeedRepositoryMockRecorder) List(ctx, folderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFeedRepository)(nil).List), ctx, folderID)
}

// ListWithoutIcon mocks base method.
func (m *MockFeedRepository) ListWithoutIcon(ctx context.Context) ([]model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithoutIcon", ctx)
	ret0, _ := ret[0].([]model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithoutIcon indicates an expected call of ListWithoutIcon.
func (mr *MockFeedRepositoryMockRecorder) ListWithoutIcon(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithoutIcon", reflect.TypeOf((*MockFeedRepository)(nil).ListWithoutIcon), ctx)
}

// Update mocks base method.
func (m *MockFeedRepository) Update(ctx context.Context, feed model.Feed) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, feed)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFeedRepositoryMockRecorder) Update(ctx, feed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeedRepository)(nil).Update), ctx, feed)
}

// UpdateErrorMessage mocks base method.
func (m *MockFeedRepository) UpdateErrorMessage(ctx context.Context, id int64, errorMessage *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateErrorMessage", ctx, id, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateErrorMessage indicates an expected call of UpdateErrorMessage.
func (mr *MockFeedRepositoryMockRecorder) UpdateErrorMessage(ctx, id, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateErrorMessage", reflect.TypeOf((*MockFeedRepository)(nil).UpdateErrorMessage), ctx, id, errorMessage)
}

// UpdateIconPath mocks base method.
func (m *MockFeedRepository) UpdateIconPath(ctx context.Context, id int64, iconPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIconPath", ctx, id, iconPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIconPath indicates an expected call of UpdateIconPath.
func (mr *MockFeedRepositoryMockRecorder) UpdateIconPath(ctx, id, iconPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIconPath", reflect.TypeOf((*MockFeedRepository)(nil).UpdateIconPath), ctx, id, iconPath)
}

// UpdateSiteURL mocks base method.
func (m *MockFeedRepository) UpdateSiteURL(ctx context.Context, id int64, siteURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSiteURL", ctx, id, siteURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSiteURL indicates an expected call of UpdateSiteURL.
func (mr *MockFeedRepositoryMockRecorder) UpdateSiteURL(ctx, id, siteURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSiteURL", reflect.TypeOf((*MockFeedRepository)(nil).UpdateSiteURL), ctx, id, siteURL)
}

// UpdateType mocks base method.
func (m *MockFeedRepository) UpdateType(ctx context.Context, id int64, feedType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateType", ctx, id, feedType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateType indicates an expected call of UpdateType.
func (mr *MockFeedRepositoryMockRecorder) UpdateType(ctx, id, feedType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateType", reflect.TypeOf((*MockFeedRepository)(nil).UpdateType), ctx, id, feedType)
}

// UpdateViewMode mocks base method.
func (m *MockFeedRepository) UpdateViewMode(ctx context.Context, id int64, viewMode *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateViewMode", ctx, id, viewMode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateViewMode indicates an expected call of UpdateViewMode.
func (mr *MockFeedRepositoryMockRecorder) UpdateViewMode(ctx, id, viewMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateViewMode", reflect.TypeOf((*MockFeedRepository)(nil).UpdateViewMode), ctx, id, viewMode)
}

// UpdateTypeByFolderID mocks base method.
func (m *MockFeedRepository) UpdateTypeByFolderID(ctx context.Context, folderID int64, feedType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTypeByFolderID", ctx, folderID, feedType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTypeByFolderID indicates an expected call of UpdateTypeByFolderID.
func (mr *MockFeedRepositoryMockRecorder) UpdateTypeByFolderID(ctx, folderID, feedType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTypeByFolderID", reflect.TypeOf((*MockFeedRepository)(nil).UpdateTypeByFolderID), ctx, folderID, feedType)
}
